#tasks:
#  - init: |
#      echo 'Geodrg 01 TODO: build project' && echo '2'
#    command: |
#    
#      echo 'Georg 02 TODO: start app' && echo '3'
tasks:
  - before: sudo apt-get install ccache -y # echo 'test before' # sh ./scripts/setup.sh
    init: ccache -M 51G #sudo apt-get install ccache -y #npm install
    command: echo "test" #sudo apt-get install ccache -y # npm run dev
  - name: Database
    init: echo 'init database' #sh ./scripts/seed-database.sh
    command: npm start-db
    env:
      DB_HOST: localhost:3306
      DB_USER: readOnlyUser
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
vscode:
 extensions:
  - ms-vscode.makefile-tools@0.3.1
# workspaceLocation: "."
